name: TDD

on:
  push:
    branches: [ main ]

jobs:
  Normal_Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permissions
      
      run: 
       chmod +x ./fake-paxos/*;
       chmod +x ./paxos_algorithm/*;
       chmod +x ./*;
    - name: Run
      run: (./run.sh fake-paxos 3)
    - name: diff files
      run: diff learn1 learn2
