name: TDD

on:
  push:
    branches: [ main ]

jobs:
  Normal_Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permissions
      
      run: 
       chmod +x ./fake-paxos/*.sh ;
       chmod +x ./fake-paxos/*.py ;
       chmod +x ./paxos_algorithm/*.sh ;
       chmod +x ./paxos_algorithm/*.py ;
       chmod +x ./*.sh ;
    - name: Run
      run: (./run.sh)
